<?php
    function meterPalabras () {
        $str = 'solicitar
        encontrar
        situación
        construir
        esperanza
        cognitivo
        condición
        reconocer
        organizar
        compartir
        resultado
        optimizar
        verificar
        descubrir
        evolución
        encuentra
        formación
        confiable
        actividad
        presentar
        respuesta
        educación
        convertir
        continuar
        mecanismo
        controlar
        propósito
        relevante
        pretender
        necesario
        conflicto
        principal
        conjetura
        proyectar
        necesidad
        descender
        delicioso
        diferente
        estimular
        describir
        reflexión
        expresión
        excelente
        presencia
        concretar
        capacidad
        contenido
        hipótesis
        seguridad
        conformar
        arrogante
        axiología
        operación
        enfrentar
        descansar
        practicar
        confirmar
        intención
        erogación
        facilitar
        recorrido
        conservar
        tendencia
        beneficio
        documento
        habilidad
        brillante
        compañero
        identidad
        despertar
        incidente
        exclusivo
        fragmento
        bienestar
        constatar
        demostrar
        dirección
        tradición
        necesitar
        posterior
        bicicleta
        económico
        categoría
        paciencia
        disfrutar
        fortaleza
        contestar
        desprecio
        comunidad
        explícito
        mencionar
        argumento
        invisible
        extensión
        apropiado
        acompañar
        cerradura
        facilidad
        funcionar
        oscuridad
        propiedad
        tranquilo
        ejercicio
        población
        ubicación
        convencer
        tolerante
        vergüenza
        corriente
        registrar
        colectivo
        inestable
        demasiado
        perseguir
        felicidad
        referente
        consultar
        maravilla
        requisito
        agradable
        conseguir
        selección
        preguntar
        inclusión
        deterioro
        saludable
        consignar
        comprobar
        destacado
        secuencia
        ecológico
        verdadero
        almacenar
        bondadoso
        atractivo
        inaugurar
        disminuir
        enseñanza
        modificar
        existente
        sustancia
        sacerdote
        coherente
        principio
        expansión
        divertido
        compuesto
        proclamar
        abandonar
        paradigma
        enfurecer
        reprender
        increíble
        inmediato
        despierto
        intervalo
        individuo
        colaborar
        actuación
        concurrir
        liderazgo
        localizar
        semejante
        obstáculo
        desempeño
        descartar
        templanza
        concordar
        cuidadoso
        ejecución
        completar
        permitirá
        constante
        preocupar
        favorecer
        desgracia
        responder
        recuperar
        impasible
        inocencia
        costumbre
        escondido
        instituir
        siguiente
        propuesta
        narración
        confianza
        sentencia
        consistir
        comercial
        implícito
        sustituir
        precisión
        xenofobia
        extinción
        emprender
        impregnar
        rimbombar
        congregar
        escenario
        finalidad
        frecuente
        averiguar
        catalizar
        coadyuvar
        ceremonia
        discusión
        pensativo
        contraste
        severidad
        inherente
        tentación
        enfatizar
        blasfemia
        movilizar
        optimista
        discrepar
        filosofía
        peligroso
        persuadir
        similitud
        reducción
        indefenso
        coordinar
        vehemente
        primitivo
        prioridad
        sensación
        solidario
        ortogonal
        cimientos
        finalizar
        abundante
        asombroso
        eficiente
        variación
        evidencia
        elementos
        instancia
        mentiroso
        prolongar
        disimular
        conversar
        inminente
        diversión
        izquierda
        inquietud
        escarpado
        perturbar
        conductor
        propiciar
        incursión
        adicional
        manipular
        denominar
        religioso
        simpático
        ignorante
        superfluo
        organismo
        cualquier
        comunicar
        inscribir
        verosímil
        conspirar
        opulencia
        repentino
        zapatilla
        nostalgia
        intimidar
        inclinado
        grandioso
        sabiduría
        coincidir
        alimentar
        preservar
        humanidad
        conmoción
        auténtico
        arrastrar
        enemistad
        intrépido
        retribuir
        imparcial
        magnífico
        prohibido
        detallado
        campestre
        preparado
        agradecer
        implantar
        potencial
        hermosura
        interesar
        asistente
        autoridad
        ponderado
        obediente
        malgastar
        excitante
        persistir
        discernir
        consentir
        impulsivo
        esplendor
        invención
        exigencia
        desterrar
        dimensión
        contrario
        capacitar
        previsión
        audiencia
        aparición
        plausible
        eutanasia
        profesión
        promulgar
        coyuntura
        solamente
        serenidad
        encuentro
        converger
        exagerado
        ideología
        cansancio
        funcional
        intuición
        confusión
        trasladar
        temerario
        imposible
        calamidad
        ictericia
        emocionar
        recóndito
        cauteloso
        violencia
        estupendo
        impresión
        lucrativo
        escritura
        inclusive
        decrépito
        ocasionar
        mensajero
        desabrido
        ratificar
        solicitud
        prototipo
        expositor
        sustentar
        minucioso
        cotidiano
        recopilar
        transitar
        gestionar
        acumulado
        innovador
        instaurar
        artificio
        potenciar
        programar
        realmente
        atravesar
        encargado
        talentoso
        inversión
        aflicción
        utensilio
        conllevar
        estipular
        comodidad
        pendiente
        emperador
        deducción
        confundir
        indolente
        felicitar
        despejado
        movilidad
        aniquilar
        sencillez
        favorable
        orgulloso
        excepción
        dinamismo
        delimitar
        incesante
        depresión
        admirable
        silvestre
        frustrado
        colección
        diligente
        encendido
        taciturno
        motivador
        oposición
        denunciar
        universal
        compasión
        dramático
        automóvil
        dispuesto
        vitalidad
        autonomía
        amonestar
        altamente
        abstracto
        focalizar
        descargar
        impecable
        obtención
        subsistir
        inmutable
        descuento
        contagiar
        proseguir
        macilento
        atreverse
        prestigio
        abastecer
        anticuado
        velocidad
        debilidad
        desenlace
        antología
        fidelidad
        decepción
        aquelarre
        comportar
        ignominia
        caudaloso
        habitante
        especular
        semblante
        ocupación
        obstinado
        antipatía
        perspicaz
        hermético
        accidente
        desplegar
        recepción
        atracción
        derrumbar
        distancia
        cambiante
        exacerbar
        analizado
        aterrador
        vestuario
        acariciar
        elemental
        semejanza
        escrúpulo
        estudioso
        referirse
        almanaque
        mercancía
        seducción
        prudencia
        altruismo
        notificar
        empleador
        incógnita
        arremeter
        maltratar
        extraviar
        campesino
        ciudadano
        emocional
        elegancia
        incentivo
        ambicioso
        subjetivo
        llamativo
        infección
        promoción
        sobriedad
        insolente
        presumido
        suspender
        minimizar
        accesible
        didáctico
        aparentar
        impetuoso
        estropear
        celestial
        psicópata
        ordinario
        protocolo
        articular
        calificar
        solitario
        fervoroso
        armonioso
        perjuicio
        perpetuar
        adiestrar
        musculoso
        aconsejar
        discordia
        prosperar
        razonable
        artefacto
        traspasar
        arriesgar
        jerarquía
        futurista
        encaminar
        personaje
        desplazar
        exactitud
        erradicar
        adjudicar
        canalizar
        sonriente
        ilusionar
        veracidad
        candidato
        sagacidad
        dilapidar
        evaluador
        dilucidar
        elocuente
        educativo
        periódico
        charlatán
        protegido
        restaurar
        infringir
        rivalidad
        recíproco
        totalidad
        aliciente
        imponente
        protector
        afectuoso
        soberanía
        ejercitar
        directriz
        acontecer
        ingenioso
        escéptico
        manicomio
        precavido
        conciliar
        zarandear
        redacción
        autorizar
        extinguir
        apaciguar
        atardecer
        homogéneo
        inclusivo
        proveedor
        vacilante
        asqueroso
        habilitar
        discípulo
        compensar
        miserable
        atrayente
        flemático
        suscribir
        diseñador
        adaptable
        postergar
        enaltecer
        homicidio
        entendido
        resguardo
        destierro
        descifrar
        hegemonía
        domicilio
        incrustar
        dinamizar
        compendio
        académico
        imitación
        simbólico
        dispensar
        accesorio
        desagrado
        industria
        sancionar
        amontonar
        distraído
        concierto
        inexperto
        merecedor
        enunciado
        atmósfera
        rememorar
        inserción
        dominante
        horizonte
        financiar
        claudicar
        propulsar
        prejuicio
        conspicuo
        caballero
        urbanidad
        concesión
        reflexivo
        primavera
        ensamblar
        supresión
        ilustrado
        fundación
        equiparar
        despachar
        exasperar
        adelantar
        conquista
        descarado
        enamorado
        indicador
        renunciar
        aceptable
        detención
        generador
        romántico
        espacioso
        custodiar
        reafirmar
        priorizar
        comprimir
        evocación
        simétrico
        obsequiar
        progresar
        remodelar
        xenofilia
        protestar
        petulante
        indudable
        propuesto
        demagogia
        libertino
        intelecto
        ecléctico
        defunción
        envejecer
        duplicado
        etiología
        tenebroso
        furibundo
        erudición
        desmedido
        aterrizar
        condensar
        vertiente
        contratar
        derrotado
        primoroso
        acrimonia
        blasfemar
        nutrición
        debilitar
        corolario
        armonizar
        derrochar
        explosión
        fenomenal
        altruista
        irrisorio
        fidedigno
        fantasear
        asequible
        incrédulo
        irregular
        intimidad
        indigente
        encantado
        utilizado
        repulsión
        bendecido
        magnánimo
        abrumador
        temporada
        presionar
        vaticinio
        rutilante
        precursor
        idolatría
        creciente
        instruido
        conocedor
        forastero
        exclusión
        embajador
        excursión
        abrasador
        destrozar
        infalible
        quimérico
        adoración
        contienda
        vigilante
        insensato
        consagrar
        etiquetar
        complicar
        permitido
        prácticas
        homologar
        aglutinar
        expresivo
        optimismo
        fragancia
        innegable
        engendrar
        legitimar
        catalogar
        iterativo
        indecente
        apreciado
        irrupción
        deambular
        desanclar
        arrebatar
        siniestro
        concernir
        ocasional
        modalidad
        arquetipo
        anticipar
        reservado
        tenacidad
        retención
        artilugio
        disculpar
        extenuado
        inusitado
        trastorno
        monumento
        desmesura
        desgastar
        sospechar
        localidad
        respaldar
        violación
        exquisito
        represión
        prolífico
        silenciar
        procesión
        disparate
        perpetrar
        hipócrita
        redención
        aprensivo
        apresurar
        remitente
        fascinado
        celeridad
        engalanar
        enganchar
        meramente
        aglomerar
        confesión
        infundado
        diseminar
        reactivar
        marginado
        ostentoso
        discurrir
        operativo
        intuitivo
        resignado
        adyacente
        santuario
        imperioso
        estiércol
        dicotomía
        preámbulo
        banalidad
        tlacuache
        elevación
        rozagante
        considera
        desvalido
        descuidar
        provisión
        concordia
        jactancia
        disturbio
        escuálido
        horroroso
        estancado
        pulcritud
        triturado
        afluencia
        inquietar
        sensorial
        solventar
        comerciar
        corrosivo
        informado
        transigir
        estupidez
        adicionar
        prevenido
        devastado
        nutritivo
        sapiencia
        ordenador
        complacer
        despótico
        escondite
        depositar
        idealista
        aeroplano
        capitular
        irritable
        reiniciar
        exponente
        frenético
        restituir
        deprimido
        productor
        ornamento
        anochecer
        proactivo
        hecatombe
        delirante
        esforzado
        clemencia
        estruendo
        concertar
        monopolio
        cobertura
        auscultar
        aplicable
        dirigente
        despuntar
        alrededor
        usufructo
        sintético
        propender
        paulatino
        asesinato
        hedonista
        idoneidad
        emancipar
        expulsión
        prematuro
        extasiado
        simulacro
        comprador
        camuflaje
        difundido
        vociferar
        avasallar
        extorsión
        recidivar
        embustero
        regenerar
        dogmático
        caducidad
        equivocar
        iluminado
        maldición
        bendición
        humanizar
        sedimento
        mediación
        melodioso
        vicisitud
        pleonasmo
        fallecido
        alarmante
        escándalo
        esotérico
        estilista
        arruinado
        centinela
        entregado
        altercado
        disgregar
        deserción
        balbucear
        carretera
        fisonomía
        eternidad
        desalmado
        residente
        riachuelo
        asombrado
        admisible
        autóctono
        tinieblas
        picaporte
        sirviente
        desglosar
        infinidad
        plantilla
        esqueleto
        servicial
        juramento
        sincronía
        indignado
        pernoctar
        acelerado
        mnemónico
        retroceso
        ilegítimo
        emboscada
        receptivo
        provincia
        vagabundo
        laberinto
        coalición
        logística
        acreditar
        inhóspito
        venerable
        despedida
        agitación
        corromper
        explosivo
        enfermizo
        permeable
        esvástica
        rutinario
        dosificar
        excedente
        congénito
        franqueza
        malcriado
        presentir
        vaticinar
        memorizar
        desahogar
        proscrito
        impreciso
        adinerado
        peregrino
        aperitivo
        condenado
        trasmitir
        oscilante
        nutriente
        aspirante
        asiduidad
        asimetría
        acusación
        garrapata
        inducción
        gentileza
        revoltoso
        memorable
        serpiente
        iniquidad
        escabroso
        testarudo
        encuadrar
        vibración
        higiénico
        congelado
        profusión
        ineptitud
        mercantil
        disensión
        ilimitado
        execrable
        engorroso
        deductivo
        desamparo
        monotonía
        oscurecer
        inanimado
        ahuyentar
        deliberar
        enseguida
        ventajoso
        pretérito
        embelesar
        sombrilla
        privación
        escultura
        codicioso
        aguerrido
        idolatrar
        vivacidad
        tempestad
        atropello
        flexionar
        minúsculo
        anotación
        segmentar
        caminante
        aherrojar
        idealizar';

        $myArray = preg_split("/[\s,]+/", $str);

        $db = new PDO('mysql:host=localhost; dbname=diccionario','root', '');
        
        $sentencia = $db->prepare("INSERT INTO palabras VALUES ('', :palabra)");
        for ($i = 0; $i < count($myArray); $i++) {
            $sentencia->bindParam(':palabra', $myArray[$i]);
            $sentencia->execute();
        }
    }

    meterPalabras();

    //echo "<pre>" . print_r(meterPalabras(), true) . "<pre>";
    


?>